---
- name: Pull Backup Configurations
  hosts: ios
  connection: network_cli
  tasks:
    - name: Playbook - Get Running Config
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: 
          dir_path: /home/sandboxadmin/ansible-cisco/backup-configs
