---
- name: Gather IOS Facts
  hosts: ios
  connection: network_cli
  tasks:
    - name: Gather IOS Facts
      ios_facts:
   
    - name: Show Appliance Version
      debug:
        var: ansible_net_version

    - name: Show Appliance Hostname
      debug:
        var: ansible_net_hostname
...
